# Generated by Django 5.2.7 on 2025-10-14 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outflows', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inflow',
            new_name='Outflow',
        ),
        migrations.RenameField(
            model_name='outflow',
            old_name='quantify',
            new_name='quantity',
        ),
    ]
