# Generated by Django 5.2.7 on 2025-10-14 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inflows', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inflow',
            old_name='quantify',
            new_name='quantity',
        ),
    ]
